manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: megamind4089
      url-base: https://github.com/megamind4089
  projects:
    - name: zmk
      remote: megamind4089
      revision: mine
      import: app/west.yml
  self:
    path: config
