on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: urob/zmk/.github/workflows/build-user-config.yml@build-with-submodules
    uses: megamind4089/zmk-config/main/.github/workflows/build.yaml@build-with-submodules
